import bookImg from "./assets/book.jpg";
import book2Img from "./assets/book2.jpg";
import organicChemImg from "./assets/organic-chem.svg";
import graphingCalculatorImg from "./assets/graphing-calculator.svg";

const placeholder = (id, w = 400, h = 300) =>
  `https://images.unsplash.com/photo-${id}?w=${w}&h=${h}&fit=crop`;

export const products = [
  {
    id: 1,
    productName: "Thomas Calculus 11th Edition",
    author: "Sarah Williams",
    price: 55,
    description: "Brand new. No writings.",
    category: "Books",
    productImage: bookImg,
  },
  {
    id: 2,
    productName: "Probability & Random Processes",
    author: "James Hugh",
    price: 49,
    description: "Fairly used, good condition.",
    category: "Books",
    productImage: book2Img,
  },
  {
    id: 3,
    productName: "Vintage Hoodie",
    author: "Alex Brown",
    price: 30,
    description: "Comfortable and warm.",
    category: "Clothing",
    productImage: placeholder("1556821840-0aaf85586236"),
  },
  {
    id: 4,
    productName: "Desk Lamp",
    author: "Sarah Williams",
    price: 25,
    description: "Perfect for study desks.",
    category: "Room Decor",
    productImage: placeholder("1524484485835-2a3e2c8e8c3a"),
  },
  {
    id: 5,
    productName: "Organic Chemistry 2nd Ed",
    author: "John Doe",
    price: 42,
    description: "Sample description of the item's current state.",
    category: "Books",
    productImage: organicChemImg,
    discountPercent: 50,
  },
  {
    id: 6,
    productName: "Graphing Calculator",
    author: "John Doe",
    price: 35,
    description: "Sample description of the item's current state.",
    category: "Books",
    productImage: graphingCalculatorImg,
    discountPercent: 56,
  },
  {
    id: 7,
    productName: "Mini Fridge 3.2 cu ft",
    author: "Taylor Chen",
    price: 95,
    description: "Great for dorm rooms and shared apartments.",
    category: "Appliances",
    productImage: placeholder("1586201375761-83865001e31f"),
  },
  {
    id: 8,
    productName: "Ergonomic Desk Chair",
    author: "Maya Patel",
    price: 68,
    description: "Adjustable height and lumbar support.",
    category: "Furniture",
    productImage: placeholder("1505798577917-a65157d3320a"),
  },
  {
    id: 9,
    productName: "Bluetooth Noise-Canceling Headphones",
    author: "Jordan Lee",
    price: 60,
    description: "Excellent for library sessions and commuting.",
    category: "Electronics",
    productImage: placeholder("1545127398-14699f92334b"),
  },
  {
    id: 10,
    productName: "Microwave Oven",
    author: "Priya Nair",
    price: 45,
    description: "Compact model, lightly used and fully functional.",
    category: "Appliances",
    productImage: placeholder("1521017432531-fbd92d768814"),
  },
  {
    id: 11,
    productName: "Desk Organizer Set",
    author: "Noah Kim",
    price: 18,
    description: "Includes pen holder, file tray, and sticky note caddy.",
    category: "School Supplies",
    productImage: placeholder("1472289065668-ce650ac443d2"),
  },
  {
    id: 12,
    productName: "Campus Bicycle",
    author: "Sofia Martinez",
    price: 120,
    description: "Smooth ride with front light and lock included.",
    category: "Transportation",
    productImage: placeholder("1511994298241-608e28f14fde"),
  },
];
