services:
  postgres:
    image: postgres:15
    container_name: hub-postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - campus-net

  backend1:
    build:
      context: ./backend/backend
      dockerfile: Dockerfile
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: ${SERVER_PORT}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SERVER_ADDRESS: ${SERVER_ADDRESS}
      APP_VERIFICATION_BASE_URL: ${APP_VERIFICATION_BASE_URL}
      APP_PASSWORD_RESET_BASE_URL: ${APP_PASSWORD_RESET_BASE_URL}
      APP_MAIL_FROM: ${APP_MAIL_FROM}
      APP_SECURITY_COOKIE_SECURE: ${APP_SECURITY_COOKIE_SECURE}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      SPRING_MAIL_SMTP_AUTH: ${SPRING_MAIL_SMTP_AUTH}
      SPRING_MAIL_SMTP_STARTTLS_ENABLE: ${SPRING_MAIL_SMTP_STARTTLS_ENABLE}
      SPRING_MAIL_SMTP_CONNECTION_TIMEOUT: ${SPRING_MAIL_SMTP_CONNECTION_TIMEOUT}
      SPRING_MAIL_SMTP_TIMEOUT: ${SPRING_MAIL_SMTP_TIMEOUT}
      SPRING_MAIL_SMTP_WRITE_TIMEOUT: ${SPRING_MAIL_SMTP_WRITE_TIMEOUT}
    networks:
      - campus-net

  frontend:
    build:
      context: ./campus-hub
      dockerfile: Dockerfile
    depends_on:
      - backend1
    networks:
      - campus-net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend1
    networks:
      - campus-net

volumes:
  postgres_data:

networks:
  campus-net: