plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.1'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.campushub'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'

java {
	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	runtimeOnly 'org.postgresql:postgresql'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-mail'
	implementation 'org.hibernate:hibernate-envers:6.2.4.Final'
	implementation 'org.togglz:togglz-spring-boot-starter:4.4.0'
	developmentOnly 'org.togglz:togglz-console:4.4.0'
	implementation 'org.modelmapper:modelmapper:2.4.4'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.5.0'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'com.stripe:stripe-java:30.1.0'
	testRuntimeOnly 'com.h2database:h2'

	// --- JWT (JJWT) ---
	// The API interface
	implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
	// The implementation (Only needed at runtime)
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
	// Jackson support for JSON parsing inside the token
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'

	// --- XML Binding (JAXB) ---
	implementation 'javax.xml.bind:jaxb-api:2.3.1'
	implementation 'org.glassfish.jaxb:jaxb-runtime:2.3.1'
}

bootJar {
	archiveFileName = 'app.jar'
	layered {
		enabled = true
	}
	classpath = classpath.filter {
		!it.name.contains('spring-boot-devtools') &&
				!it.name.contains('togglz-console')
//				!it.name.contains('springdoc-openapi-starter-webmvc-ui')
	}
}

tasks.named('test') {
	useJUnitPlatform()
}
